---
- name: Install dependencies
  become: true
  apt:
    name:
      - libavutil56
      - libcairo-gobject2
      - libgtk-3-0
      - libqtgui4
      - libpango-1.0-0
      - libqtcore4
      - libavcodec58
      - libcairo2
      - libswscale5
      - libtiff5
      - libqt4-test
      - libatk1.0-0
      - libavformat58
      - libgdk-pixbuf2.0-0
      - libilmbase23
      - libjasper1
      - libopenexr23
      - libpangocairo-1.0-0
      - libwebp6
      - libhdf5-dev
      - libhdf5-serial-dev
      - libhdf5-103
      - libatlas-base-dev

- name: Install opencv-contrib-python
  pip:
    name:
      - opencv-contrib-python==4.1.0.25
