---
- name: hostname
  command:
    cmd: raspi-config nonint do_hostname {{ hostname }}

- name: timezone
  command:
    cmd: raspi-config nonint do_change_timezone Asia/Tokyo

- name: locale
  command:
    cmd: raspi-config nonint do_change_locale ja_JP.UTF-8
