---
- name: Edit /etc/systemd/timesyncd.conf
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#NTP='
      line: 'NTP={{ ntp }}'
    - regexp: '^#FallbackNTP='
      line: 'FallbackNTP={{ fallback }}'

- name: timedatectl set-ntp true
  command:
    cmd: timedatectl set-ntp true

- name: Daemon reload
  systemd:
    daemon_reload: yes

- name: Service restart
  systemd:
    name: systemd-timesyncd.service
    state: restarted
